[nitpick.meta]
name = "EditorConfig"
url = "http://editorconfig.org/"

[".editorconfig"]
# top-most EditorConfig file
root = true

[".editorconfig"."*"]
# Unix-style newlines with a newline ending every file
end_of_line = "lf"
insert_final_newline = true
indent_style = "space"
indent_size = 2
charset = "utf-8"

# Whitespace at the end of lines
trim_trailing_whitespace = true

[".editorconfig"."*.py"]
indent_size = 4

# Tab indentation (no size specified)
[".editorconfig".Makefile]
indent_style = "tab"
